requirements.txt: fix bdist_wheel missing dependency
CI started complaining about this

```
Building wheels for collected packages: django-allauth, coreschema
  Building wheel for django-allauth (pyproject.toml): started
  Building wheel for django-allauth (pyproject.toml): finished with status 'done'
  Created wheel for django-allauth: filename=django_allauth-65.7.0-py3-none-any.whl size=1773875 sha256=b1e3674ae42d28a42ebe3192d2bcabfdb3406fdc396e8ebcd277bf5ef977142c
  Stored in directory: /root/.cache/pip/wheels/40/81/98/7b9df9de05b2d919cab48dd38e27dda7665beb28af39883157
  Building wheel for coreschema (setup.py): started
  Building wheel for coreschema (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for coreschema
  Running setup.py clean for coreschema
Successfully built django-allauth
Failed to build coreschema
ERROR: Could not build wheels for coreschema, which is required to install pyproject.toml-based projects
```

Signed-off-by: Charles Oliveira <charles.oliveira@linaro.org>